################
# build matrix #
################

before_script:
    - sudo apt-get install libopenmpi-dev openmpi-bin libboost-all-dev cmake


################
# build script #
################

build:
  script:
    # compile and execute unit tests
    - mkdir -p build && cd build
    - cmake .. ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS_RELEASE=-O3 && cmake --build . --config Release
    - ctest -C Release -V -j
    - cd ..
