##########
# Set-up #
##########

stages:
  - build

#################
# Build Configs #
#################

openmpi_ubuntu16_test:
  stage: build
  image: ubuntu:16.04
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake python3.6 python-numpy
    - bash .gitlab-ci-test-and-cov.sh


openmpi_ubuntu17_test:
  stage: build
  # image: ubuntu:17.10
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake python3.6 python-numpy
    - bash .gitlab-ci-test-and-cov.sh




mpich_ubuntu16_test:
  stage: build
  image: ubuntu:16.04
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake python3.6 python-numpy
    - bash .gitlab-ci-test-and-cov.sh


mpich_ubuntu17_test:
  stage: build
  # image: ubuntu:17.10
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake python3.6 python-numpy
    - bash .gitlab-ci-test-and-cov.sh
