##################
# Configurations #
##################

# Testing openmpi compiling on linux
linux_openmpi:
  script:
    - apt-get -qq update && apt-get -qq install -y libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

# Testing mpich compiling on linux
linux_mpich:
  script:
    - apt-get -qq update && apt-get -qq install -y libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice
