################
# build matrix #
################

before_script:
  - apt-get -qq update && apt-get -qq install -y libopenmpi-dev openmpi-bin libboost-all-dev cmake


################
# build script #
################

# MPI
mpi:
  script:
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice
    # - cmake .. ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS_RELEASE=-O3 && cmake --build . --config Release
    # - ctest -C Release -V -j
    # - cd ..

# Serial
# serial:
#   script:
#     - mkdir -p build && cd build
#     - cmake ..
#     - make -j DiceSerial
