##########
# Set-up #
##########

stages:
  - build
  - test

#################
# Build Configs #
#################

# Openmpi test builds
openmpi_ubuntu16:
  stage: build
  image: ubuntu:16.04
  script:
    - apt-get -qq update && apt-get -qq install -y libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

openmpi_ubuntu17:
  stage: build
  image: ubuntu:17.10
  script:
    - apt-get -qq update && apt-get -qq install -y libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

# Testing mpich compiling on different versions of ubuntu
mpich_ubuntu16:
  stage: build
  image: ubuntu:16.04
  script:
    - apt-get -qq update && apt-get -qq install -y libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

mpich_ubuntu17:
  stage: build
  image: ubuntu:17.10
  script:
    - apt-get -qq update && apt-get -qq install -y libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - which mpicxx
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

#########
# Tests #
#########

simple_test:
  stage: test
  script:
    - cd tests/o2_omp1_det
    - ../../build/Dice
