##########
# Set-up #
##########

stages:
  - build
  - test

#################
# Build Configs #
#################

openmpi_ubuntu16:
  stage: build
  image: ubuntu:16.04
  artifacts:
    untracked: true
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

openmpi_ubuntu17:
  stage: build
  image: ubuntu:17.10
  artifacts:
    untracked: true
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

mpich_ubuntu16:
  stage: build
  image: ubuntu:16.04
  artifacts:
    untracked: true
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

mpich_ubuntu17:
  stage: build
  image: ubuntu:17.10
  artifacts:
    untracked: true
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - export CXX=mpicxx
    - mkdir -p build && cd build
    - cmake ..
    - make -j Dice

#########
# Tests #
#########

openmpi_ubuntu16_test:
  stage: test
  image: ubuntu:16.04
  dependencies:
    - openmpi_ubuntu16
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - cd tests/o2_omp1_det
    - ../../build/Dice
    - mpirun -n 2 ../../build/Dice --allow-run-as-root

openmpi_ubuntu17_test:
  stage: test
  # image: ubuntu:17.10
  dependencies:
    - openmpi_ubuntu17
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libopenmpi-dev openmpi-bin libboost-all-dev cmake
    - cd tests/o2_omp1_det
    - ../../build/Dice
    - mpirun -n 2 ../../build/Dice --allow-run-as-root

mpich_ubuntu16_test:
  stage: test
  image: ubuntu:16.04
  dependencies:
    - mpich_ubuntu16
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - cd tests/o2_omp1_det
    - ../../build/Dice
    - mpirun -n 2 ../../build/Dice --allow-run-as-root

mpich_ubuntu17_test:
  stage: test
  # image: ubuntu:17.10
  dependencies:
    - mpich_ubuntu17
  script:
    - apt-get -qq update
    - apt-get -qq install -y g++ libcr-dev mpich libmpich-dev libboost-all-dev cmake
    - cd tests/o2_omp1_det
    - ../../build/Dice
    - mpirun -n 2 ../../build/Dice --allow-run-as-root
